batch_size: 32
num_epochs: 1
patience: 10
model:
  trunk:
    backbone: resnet18
    # Check this link for details on the preprocessing: https://pytorch.org/vision/stable/models/generated/torchvision.models.resnet18.html#torchvision.models.resnet18
    preprocessing:
      values:
        dtype: float32
        scale: true
      crop_size: 224
      normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  embedder:
    embedding_size: 128
    hidden_layer_sizes:
      - 256
loss:
  type: circleloss
  config:
    m: 0.4
    gamma: 256
optimizers:
  embedder:
    type: adam
    config:
      lr: 0.001
      weight_decay: 0.0
  trunk:
    type: adam
    config:
      lr: 0.001
      weight_decay: 0.0
