batch_size: 32
num_epochs: 50
data_augmentation:
  config: {}
model:
  trunk:
    backbone: resnet18
  embedder:
    embedding_size: 128
    hidden_layer_sizes:
      - 1024
loss:
  type: tripletmarginloss
  config:
    margin: 0.5
sampler:
  type: mperclass
  config:
    m: 4
optimizers:
  embedder:
    type: adam
    config:
      lr: 0.001
      weight_decay: 0.0
  trunk:
    type: adam
    config:
      lr: 0.0001
      weight_decay: 0.0
miner:
  type: batcheasyhardminer
  config:
    pos_strategy: semihard
    neg_strategy: hard
